Add ability to install personal packages

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -40,11 +40,15 @@ install() {
   elif [ $OS == "darwin" ]; then
     has_brew=$(command -v brew >/dev/null)
     if $has_brew; then
-      brew install $brew_package_name
-      exit_code=$?
-      if [ $exit_code != 0 ]; then
-        echo "  Installation Failed. Exiting."
-        exit $exit_code
+      if brew list $brew_package_name > /dev/null; then
+        echo "  Already installed! Skipping."
+      else
+        brew install $brew_package_name
+        exit_code=$?
+        if [ $exit_code != 0 ]; then
+          echo "  Installation Failed. Exiting."
+          exit $exit_code
+        fi
       fi
     else
       echo "  Homebrew wasn't found!"
@@ -100,6 +104,7 @@ setup_vim() {
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   fi
 
+  echo "Installing Vim plugins"
   vim +"PlugInstall --sync" +qa > /dev/null 2>&1
   mkdir -p ~/.vim/tmp
 }
@@ -164,6 +169,16 @@ install_rubies() {
   link ".gemrc"
 }
 
+install_personal_packages() {
+  echo "Preparing to install packages from ~/.package_list"
+  copy ".package_list"
+  echo "Please make sure your personal package list in ~/.package_list is up to date before continuing."
+  read -rsp $'Press any key to continue...\n'
+  for package in $(cat ~/.package_list); do
+    install "$package" "$package"
+  done
+}
+
 link ".ackrc" &&
 setup_bash &&
 setup_git &&
@@ -173,4 +188,5 @@ install_packer &&
 install_rubies &&
 install jq jq &&
 install tree tree &&
+install_personal_packages &&
 echo "You're good to go. Customize .gitconfig.local and you'll be off to the races!"
